repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.4
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix, --config, pyproject.toml]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]
        args: [--config, pyproject.toml]