services:
  silvr:
    container_name: silvr_container
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    network_mode: "host"
    tty: true
    # volumes:
    #     - /home/yifu/data:/home/docker_dev/data

    