services:
  silvr:
    container_name: silvr_container
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
        - USERNAME=${USERNAME}
        - DOCKER_HOME_DIR=${DOCKER_HOME_DIR}
        - DOCKER_WORK_DIR=${DOCKER_WORK_DIR}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    network_mode: "host"
    tty: true
    volumes:
        - ${HOST_DATA_DIR}:${DOCKER_DATA_DIR}
        - ../scripts:${DOCKER_WORK_DIR}/scripts
        - ../configs:${DOCKER_WORK_DIR}/configs
    